from django.db import models

class DataEntry(models.Model):
    end_year = models.CharField(max_length=10, blank=True, null=True)
    intensity = models.IntegerField(blank=True,null=True,default='')
    sector = models.CharField(max_length=100, blank=True, null=True)
    topic = models.CharField(max_length=100)
    insight = models.TextField()
    url = models.URLField()
    region = models.CharField(max_length=100)
    start_year = models.CharField(max_length=10, blank=True, null=True)
    impact = models.CharField(max_length=10, blank=True, null=True)
    added = models.DateTimeField()
    published = models.DateTimeField(blank=True,null=True,default='')
    country = models.CharField(max_length=100, blank=True, null=True)
    relevance = models.IntegerField(null=True,blank=True)
    pestle = models.CharField(max_length=100)
    source = models.CharField(max_length=100)
    title = models.TextField()
    likelihood = models.IntegerField(null=True,blank=True,default='')
